version: "3.8"

services:
  vegetable-app1:
    build: .
    image: vegetable-app:v2.0.0 
    container_name: vegetable-web-app
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vegetable_order_app
      
    depends_on:
      - mongo
      
    networks:
      - vegetable-network
      

  mongo:
    image:  mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - vegetable-network


networks:
  vegetable-network:
    driver: bridge
